### ISSUE TITLE
What is Terms of License ? 

### ISSUE THREAD

**Issue by jungbum** [christopherney/FlatDatePicker#12]
I love your control. And I am planning to modify it and use it in my project.
But you didn't mentioned License of this code.
 I want to know license of this code.

**Comment by christopherney** [comment]
Thank, you can used this component without problem, it's totally free and open source.

**Comment by jungbum** [comment]
Thank you so much.
May God bless you !
And...how about clearly mention terms of  License  in the main page like other repository?
If you do  I think people may  feel comfortable with it.
