### ISSUE TITLE
Nice control but does not work for the demo

### ISSUE THREAD

**Issue by skywalkerlw** [christopherney/FlatDatePicker#3]
![img_0378](https://f.cloud.github.com/assets/2090084/841400/91a131f4-f392-11e2-906d-eb51bec7cef9.PNG)

I downloaded and did no changes. I can build but fail to run and show the date picker. 

See attached.

**Comment by christopherney** [comment]
Hi, have you try to disabled the breakpoints ?

**Comment by skywalkerlw** [comment]
There's no breakpoints at all, I'm working on xcode4.6.3 and iOS6.1 simulator

**Comment by ghost** [comment]
In my case it crashes with:
2013-09-16 16:31:34.070 FlatDatePicker[5741:c07] **\* Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named NSLayoutConstraint'

**Comment by ghost** [comment]
solution: turn autolayout off
